// Code generated by modgen. DO NOT EDIT.
package .

import (
	"alloy/models/contract"
	"reflect"
	appstore "alloy/models/appstore"
	usermanager "alloy/models/usermanager"
)

func ifaceOf[T any]() reflect.Type {
	return reflect.TypeOf((*T)(nil)).Elem()
}

func (m *Module) Manifest() contract.Manifest {
	return contract.Manifest{
		Name:    "AppStore",
		Version: "0.0.1",
		Summary: "App store with apps, purchases, and license management",
		Provides: []contract.PortSpec{
			{Name: "AppStore", Iface: ifaceOf[appstore.AppStore]()},
		},
		Requires: []contract.PortSpec{
			{Name: "UserManager", Iface: ifaceOf[usermanager.UserManager]()},
		},
		Permissions: []contract.Permission{
		},
		Events: []contract.EventSpec{
		},
		Migrations: nil,
	}
}
func ProvideAppStore(reg *contract.Registry, impl appstore.AppStore) {
	reg.Provide(ifaceOf[appstore.AppStore](), impl)
}
func RequireUserManager(reg *contract.Registry) usermanager.UserManager {
	return contract.RequireT[usermanager.UserManager](reg)
}
