// Code generated by modgen. DO NOT EDIT.
package usermanager

import (
	"alloy/models/contract"
	"reflect"
	auth "alloy/models/auth"
	usermanager "alloy/models/usermanager"
)

func ifaceOf[T any]() reflect.Type {
	return reflect.TypeOf((*T)(nil)).Elem()
}

func (m *Module) Manifest() contract.Manifest {
	return contract.Manifest{
		Name:    "UserManager",
		Version: "0.0.1",
		Summary: "User management module",
		Provides: []contract.PortSpec{
			{Name: "UserManager", Iface: ifaceOf[usermanager.UserManager]()},
		},
		Requires: []contract.PortSpec{
		},
		Permissions: []contract.Permission{
		},
		Events: []contract.EventSpec{
			{Name: "auth.user.logged_in", Direction: contract.EventSubscribed, Payload: reflect.TypeOf((*auth.LoginEvent)(nil)).Elem()},
		},
		Migrations: nil,
	}
}
func ProvideUserManager(reg *contract.Registry, impl usermanager.UserManager) {
	reg.Provide(ifaceOf[usermanager.UserManager](), impl)
}
