// Code generated by modgen. DO NOT EDIT.
package service

func (s *Service) CreateApp(input CreateAppInput) (App, error) {
	return *new(App), *new(error)
}

func (s *Service) GetAppByID(id int64) (App, error) {
	return *new(App), *new(error)
}

func (s *Service) GetAppByAppID(appID string) (App, error) {
	return *new(App), *new(error)
}

func (s *Service) GetAllApps() ([]App, error) {
	return *new([]App), *new(error)
}

func (s *Service) UpdateApp((id int64, input UpdateAppInput)) (App, error) {
	return *new(App), *new(error)
}

func (s *Service) DeleteApp(id int64) error {
	return *new(error)
}

func (s *Service) GetHomeSections() ([]HomeSection, error) {
	return *new([]HomeSection), *new(error)
}

func (s *Service) GetPinnedApps() ([]App, error) {
	return *new([]App), *new(error)
}

func (s *Service) SearchApps(query string) ([]App, error) {
	return *new([]App), *new(error)
}

func (s *Service) GetAppStats() (int64, error) {
	return *new(int64), *new(error)
}

func (s *Service) AddPurchase((userID int64, appID int64, expiryDays int)) (Purchase, error) {
	return *new(Purchase), *new(error)
}

func (s *Service) RemovePurchase(id int64) error {
	return *new(error)
}

func (s *Service) GetUserPurchases(userID int64) ([]Purchase, error) {
	return *new([]Purchase), *new(error)
}

func (s *Service) VerifyLicense((userID int64, appID string)) (bool, error) {
	return *new(bool), *new(error)
}

func (s *Service) RegenerateLicenseKey(purchaseID int64) (string, error) {
	return *new(string), *new(error)
}
