// Code generated by modgen. DO NOT EDIT.
package boot

import (
	"alloy/internal/app/config"
	"alloy/models/contract"
)

func Modules(cfg config.Config, log func(string)) []contract.Module {
	return []contract.Module{
	}
}
