// Code generated by modgen. DO NOT EDIT.
package service

import (
	contract "alloy/models/contract"
	cache "alloy/internal/platform/cache"
	usermanager "alloy/models/usermanager"
)

type BaseService struct {
	Runtime contract.Runtime
	Cache   *cache.Cache
	UserManager usermanager.UserManager
}

func NewBaseService(rt contract.Runtime, UserManager usermanager.UserManager) BaseService {
	return BaseService{
		Runtime: rt,
		UserManager: UserManager,
	}
}
