// Code generated by modgen. DO NOT EDIT.
package service

import (
	contract "alloy/models/contract"
	cache "alloy/internal/platform/cache"
)

type BaseService struct {
	Runtime contract.Runtime
	Cache   *cache.Cache
}

func NewBaseService(rt contract.Runtime) BaseService {
	return BaseService{
		Runtime: rt,
	}
}
