// Code generated by modgen. DO NOT EDIT.
package auth

import (
	"alloy/models/contract"
	"reflect"
	auth "alloy/models/auth"
	usermanager "alloy/models/usermanager"
)

func ifaceOf[T any]() reflect.Type {
	return reflect.TypeOf((*T)(nil)).Elem()
}

func (m *Module) Manifest() contract.Manifest {
	return contract.Manifest{
		Name:    "Auth",
		Version: "0.0.1",
		Summary: "Authentication module",
		Provides: []contract.PortSpec{
			{Name: "Auth", Iface: ifaceOf[auth.AuthService]()},
		},
		Requires: []contract.PortSpec{
			{Name: "UserManager", Iface: ifaceOf[usermanager.UserManager]()},
		},
		Permissions: []contract.Permission{
		},
		Events: []contract.EventSpec{
			{Name: "auth.user.logged_in", Direction: contract.EventPublished, Payload: reflect.TypeOf((*auth.LoginEvent)(nil)).Elem()},
		},
		Migrations: nil,
	}
}
func ProvideAuth(reg *contract.Registry, impl auth.AuthService) {
	reg.Provide(ifaceOf[auth.AuthService](), impl)
}
func RequireUserManager(reg *contract.Registry) usermanager.UserManager {
	return contract.RequireT[usermanager.UserManager](reg)
}
